models:
  - type: main
    engine: openai
    model: gpt-4
    parameters:
      temperature: 0.7
      max_tokens: 500

rails:
  config:
    core:
      language_model: main
    flows:
      - flows.co

instructions:
  - type: general
    content: |
      You are a helpful AI assistant that provides information based on the given context.
      Always be truthful and accurate in your responses.
      If you're unsure about something or if the information isn't in the context, admit it rather than making assumptions.
      Base your responses strictly on the provided context.

  - type: input
    content: |
      Ensure the user's input is appropriate and on-topic.
      Reject any harmful, offensive, or inappropriate content.

  - type: output
    content: |
      Ensure responses are:
      1. Factually accurate based on the provided context
      2. Professional and helpful
      3. Free from harmful or inappropriate content
      4. Clear and well-structured