name: llamaindex-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - llama-index==0.9.8
    - python-dotenv==1.0.0
    - pypdf==3.17.1
    - transformers==4.35.2
    - torch==2.1.1
    - sentence-transformers==2.2.2
    - accelerate==0.27.2
    - rich==13.7.0
