name: mongodb-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pymongo==4.6.1
    - python-dotenv==1.0.0
    - openai==1.3.7
    - langchain==0.0.350
    - chromadb==0.4.18
    - tiktoken==0.5.2
    - python-magic==0.4.27
    - beautifulsoup4==4.12.2
    - requests==2.31.0
