name: haystack-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0.1
  - pip:
    - haystack-ai>=0.0.1
    - torch>=2.0.0
    - sentence-transformers>=2.2.2
    - faiss-cpu>=1.7.4
    - pypdf>=3.9.0
    - openai>=1.3.0
    - python-dotenv>=1.0.0
    - ipykernel
    - jupyter
    - notebook
